# Generated by Django 6.1 on 2026-09-26 16:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0001_initial'),
        ('licensing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuarterlyReturn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('financial_year', models.CharField(max_length=9)),
                ('quarter', models.CharField(choices=[('Q1', 'Q1 (Apr-Jun)'), ('Q2', 'Q2 (Jul-Sep)'), ('Q3', 'Q3 (Oct-Dec)'), ('Q4', 'Q4 (Jan-Mar)')], max_length=2)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('LATE_SUBMITTED', 'Submitted Late'), ('OVERDUE', 'Overdue')], default='DRAFT', max_length=15)),
                ('total_manufactured', models.PositiveIntegerField(default=0)),
                ('total_sold', models.PositiveIntegerField(default=0)),
                ('total_repaired', models.PositiveIntegerField(default=0)),
                ('submission_date', models.DateTimeField(blank=True, null=True)),
                ('due_date', models.DateField()),
                ('late_fee_paid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='businesses.business')),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='licensing.license')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submitted_returns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-financial_year', '-quarter'],
                'unique_together': {('license', 'financial_year', 'quarter')},
            },
        ),
        migrations.CreateModel(
            name='ProductionRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('instrument_type', models.CharField(max_length=100)),
                ('quantity_manufactured', models.PositiveIntegerField()),
                ('remarks', models.TextField(blank=True)),
                ('quarterly_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_records', to='compliance.quarterlyreturn')),
            ],
        ),
        migrations.CreateModel(
            name='RepairRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('instrument_type', models.CharField(max_length=100)),
                ('owner_name', models.CharField(max_length=200)),
                ('nature_of_repair', models.TextField()),
                ('repair_date', models.DateField()),
                ('verification_certificate_number', models.CharField(blank=True, max_length=100)),
                ('quarterly_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repair_records', to='compliance.quarterlyreturn')),
            ],
        ),
        migrations.CreateModel(
            name='SaleRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('instrument_type', models.CharField(max_length=100)),
                ('buyer_name', models.CharField(max_length=200)),
                ('buyer_address', models.TextField()),
                ('quantity', models.PositiveIntegerField()),
                ('dispatch_date', models.DateField()),
                ('invoice_number', models.CharField(blank=True, max_length=50)),
                ('quarterly_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_records', to='compliance.quarterlyreturn')),
            ],
        ),
    ]
