# Generated by Django 6.1 on 2026-08-31 06:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('result', models.CharField(blank=True, choices=[('PASS', 'Pass'), ('FAIL', 'Fail'), ('REQUIRES_CORRECTION', 'Requires correction')], max_length=20)),
                ('notes', models.TextField(blank=True, max_length=2000)),
                ('gps_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('gps_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('gps_accuracy_meters', models.PositiveIntegerField(blank=True, null=True)),
                ('captured_at', models.DateTimeField(blank=True, null=True)),
                ('client_operation_id', models.UUIDField(blank=True, null=True, unique=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='inspection', to='applications.application')),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inspections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=100)),
                ('nominal_value', models.DecimalField(decimal_places=3, max_digits=12)),
                ('observed_value', models.DecimalField(decimal_places=3, max_digits=12)),
                ('unit', models.CharField(max_length=10)),
                ('within_tolerance', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='inspections.inspection')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
