# Generated by Django 6.1 on 2026-09-26 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='constitution_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='gst_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='is_dealer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='business',
            name='is_manufacturer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='business',
            name='is_packer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='business',
            name='is_repairer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='business',
            name='pan_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='pincode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
