# Generated by Django 6.1 on 2026-09-04 09:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('APPLICATION_UPDATE', 'Application update'), ('SCHEDULE_UPDATE', 'Visit scheduled or moved'), ('INSPECTION_RESULT', 'Inspection result'), ('CERTIFICATE_ISSUED', 'Certificate issued'), ('CERTIFICATE_REVOKED', 'Certificate revoked'), ('EXPIRY_WARNING', 'Certificate expiry warning'), ('SYNC_RESULT', 'Offline sync outcome'), ('GENERAL', 'General')], default='GENERAL', max_length=25)),
                ('title', models.CharField(max_length=150)),
                ('message', models.TextField(max_length=500)),
                ('related_entity_type', models.CharField(blank=True, max_length=30)),
                ('related_entity_id', models.UUIDField(blank=True, null=True)),
                ('link', models.CharField(blank=True, max_length=300)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='businesses.business')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'read_at', '-created_at'], name='notificatio_recipie_ce9d56_idx'), models.Index(fields=['related_entity_type', 'related_entity_id'], name='notificatio_related_9087d9_idx')],
            },
        ),
    ]
