import { Instrument, VerificationApplication, VerificationCertificate, Officer, AuditLog, NotificationItem } from './types';

export const initialInstruments: Instrument[] = [
  {
    id: 'INST-2026-98241',
    serialNumber: 'SN-88219-X',
    type: 'Electronic Weighing Scale (Class II)',
    manufacturer: 'Precision Tech Industries',
    modelNumber: 'PT-Scale-XPro',
    accuracyClass: 'Class II (High Accuracy)',
    capacity: '15.000 kg',
    resolution: '0.005 kg',
    location: 'G-Block Market, Sector 14, New Delhi - 110001',
    status: 'ACTIVE',
    nextDue: '14 Oct 2026',
    registeredDate: '01 Sep 2025',
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuD2PrhbZ_pNKm7GywFCjjDbFGXiV13BbeC1WdgPojM-rqNQNBjLckN75yZqMs4P7K_o-ieKRN9nHWZ7HeOdfjpqCgNlFFUfFFyKSkEYlLt7E2Y9KXRNLMgV54qfjWPUfsSpJviATb6cAjUNQKblo-j5PcTKRqoRlfbX9aXG79YcJJDIORoMLSZcGJxwuB13TSIsGlsxjVOZIaSPJhZd9Gp8T3rmJvnu-nZYIhcqMqtCje0xAKPWCOtN',
    merchantName: 'Demo Retail Store',
    merchantAddress: 'G-Block Market, Sector 14, New Delhi - 110001',
    lastInspectionDate: '14 Oct 2025',
    inspectorName: 'Inspector Ramesh Kumar',
    certificateId: 'CERT-DEMO-001',
    lifecycle: [
      {
        title: 'Registered',
        date: '01 Sep 2025',
        description: 'Instrument profile created by merchant.',
        type: 'registered',
      },
      {
        title: 'Verification Application',
        date: '05 Sep 2025',
        description: 'Fee paid and application accepted.',
        type: 'application',
      },
      {
        title: 'Inspection Completed',
        date: '14 Oct 2025',
        description: 'Physical inspection completed by Inspector Ramesh Kumar. Device seals are visually intact.',
        type: 'inspection',
        reportLink: true,
      },
      {
        title: 'Certificate Issued',
        date: '15 Oct 2025',
        description: 'Digital tamper-proof verification certificate issued.',
        type: 'certificate',
        pdfDownload: true,
        validUntil: '14 Oct 2026',
      },
    ],
  },
  {
    id: 'INS-2025-8839',
    serialNumber: 'SN-A1B2-990',
    type: 'Platform Scale',
    manufacturer: 'PreciseTech Ind.',
    modelNumber: 'PS-500-Heavy',
    accuracyClass: 'Class III (Medium Accuracy)',
    capacity: '500.00 kg',
    resolution: '0.05 kg',
    location: 'Warehouse 4B, Okhla Industrial Area Ph-III, Delhi',
    status: 'ACTIVE',
    nextDue: '12 Oct 2026',
    registeredDate: '10 Aug 2025',
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuD2PrhbZ_pNKm7GywFCjjDbFGXiV13BbeC1WdgPojM-rqNQNBjLckN75yZqMs4P7K_o-ieKRN9nHWZ7HeOdfjpqCgNlFFUfFFyKSkEYlLt7E2Y9KXRNLMgV54qfjWPUfsSpJviATb6cAjUNQKblo-j5PcTKRqoRlfbX9aXG79YcJJDIORoMLSZcGJxwuB13TSIsGlsxjVOZIaSPJhZd9Gp8T3rmJvnu-nZYIhcqMqtCje0xAKPWCOtN',
    merchantName: 'Metro Logistics Hub',
    merchantAddress: 'Warehouse 4B, Okhla Industrial Area, Delhi',
    lastInspectionDate: '12 Oct 2025',
    inspectorName: 'Insp. Sharma',
    certificateId: 'CERT-992',
    lifecycle: [
      {
        title: 'Registered',
        date: '10 Aug 2025',
        description: 'Profile registered under Legal Metrology Act.',
        type: 'registered',
      },
      {
        title: 'Verification Application',
        date: '15 Aug 2025',
        description: 'Re-verification fee ₹850 paid online.',
        type: 'application',
      },
      {
        title: 'Inspection Completed',
        date: '12 Oct 2025',
        description: 'Standard calibrated weights applied up to 500kg. Error is within ±1e tolerance.',
        type: 'inspection',
        reportLink: true,
      },
      {
        title: 'Certificate Issued',
        date: '12 Oct 2025',
        description: 'Valid certificate issued with QR Passport.',
        type: 'certificate',
        pdfDownload: true,
        validUntil: '12 Oct 2026',
      },
    ],
  },
  {
    id: 'INS-2025-1102',
    serialNumber: 'FD-XZ-2021',
    type: 'Fuel Dispenser Pump',
    manufacturer: 'PetroEquip Global',
    modelNumber: 'PEG-FuelFlow-Dual',
    accuracyClass: 'Class 0.5 (Liquids)',
    capacity: '60 Litres/min',
    resolution: '0.01 Litre',
    location: 'Fuel Station 18, Ring Road, South Ext, New Delhi',
    status: 'EXPIRED',
    nextDue: '01 Jan 2026',
    registeredDate: '15 Dec 2024',
    merchantName: 'Ganga Fuel Station',
    merchantAddress: 'Ring Road, South Ext, New Delhi',
    lastInspectionDate: '01 Jan 2025',
    inspectorName: 'Officer Patel',
    certificateId: 'CERT-EXP-004',
    lifecycle: [
      {
        title: 'Registered',
        date: '15 Dec 2024',
        description: 'Fuel nozzle dispenser registration.',
        type: 'registered',
      },
      {
        title: 'Inspection Completed',
        date: '01 Jan 2025',
        description: '5L & 10L volumetric measure test completed.',
        type: 'inspection',
        reportLink: true,
      },
      {
        title: 'Certificate Expired',
        date: '01 Jan 2026',
        description: 'Annual calibration validity has lapsed. Re-verification required.',
        type: 'certificate',
        pdfDownload: true,
        validUntil: '01 Jan 2026',
      },
    ],
  },
  {
    id: 'INS-2024-7741',
    serialNumber: 'WB-99-XX',
    type: 'Weighbridge 50T',
    manufacturer: 'HeavyMass Ltd.',
    modelNumber: 'HM-WB-50000',
    accuracyClass: 'Class IV (Ordinary Accuracy)',
    capacity: '50,000 kg',
    resolution: '10.0 kg',
    location: 'Inland Container Depot, Tughlakabad, New Delhi',
    status: 'ACTIVE',
    nextDue: '05 Nov 2026',
    registeredDate: '20 Oct 2024',
    merchantName: 'Kisan Logistics Pvt Ltd',
    merchantAddress: 'Container Depot, Tughlakabad, Delhi',
    lastInspectionDate: '05 Nov 2025',
    inspectorName: 'Insp. Sharma',
    certificateId: 'CERT-2026-X99',
    lifecycle: [
      {
        title: 'Registered',
        date: '20 Oct 2024',
        description: 'Pitless weighbridge initial onboarding.',
        type: 'registered',
      },
      {
        title: 'Inspection Completed',
        date: '05 Nov 2025',
        description: 'Standard dead weights and corner shift test conducted.',
        type: 'inspection',
        reportLink: true,
      },
      {
        title: 'Certificate Issued',
        date: '05 Nov 2025',
        description: 'Stamped with official Legal Metrology lead seal.',
        type: 'certificate',
        pdfDownload: true,
        validUntil: '05 Nov 2026',
      },
    ],
  },
];

export const initialCertificates: Record<string, VerificationCertificate> = {
  'CERT-DEMO-001': {
    certificateNumber: 'CERT-DEMO-001',
    instrumentId: 'INS-DEMO-001',
    instrumentType: 'Electronic Scale',
    manufacturer: 'Precision Tech Industries',
    serialNumber: 'SN-88219-X',
    issuedDate: '01 Sep 2026',
    validUntil: '01 Sep 2027',
    status: 'VALID',
    signatureVerified: true,
    payloadIntegrityVerified: true,
    sha256Hash: 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855',
    issuedByOfficer: 'Inspector Ramesh Kumar (ID: LM-DL-042)',
    issuedAtOffice: 'Legal Metrology Department, Govt. of NCT of Delhi',
    merchantName: 'Demo Retail Store',
    merchantAddress: 'G-Block Market, Sector 14, New Delhi - 110001',
    qrPayload: 'https://mapansetu.gov.in/verify/CERT-DEMO-001',
  },
  'CERT-992': {
    certificateNumber: 'CERT-992',
    instrumentId: 'INS-2025-8839',
    instrumentType: 'Electronic Weighing Scale',
    manufacturer: 'PreciseTech Ind.',
    serialNumber: 'SN-A1B2-990',
    issuedDate: '12 Oct 2025',
    validUntil: '12 Oct 2026',
    status: 'VALID',
    signatureVerified: true,
    payloadIntegrityVerified: true,
    sha256Hash: '9a8f276c98c11e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca49',
    issuedByOfficer: 'Insp. Sharma (ID: LM-DL-019)',
    issuedAtOffice: 'Legal Metrology South Zone, New Delhi',
    merchantName: 'Demo Retail Store',
    merchantAddress: 'G-Block Market, Sector 14, New Delhi',
    qrPayload: 'https://mapansetu.gov.in/verify/CERT-992',
  },
  'CERT-2026-X99': {
    certificateNumber: 'CERT-2026-X99',
    instrumentId: 'INS-2024-7741',
    instrumentType: 'Weighbridge 50T',
    manufacturer: 'HeavyMass Ltd.',
    serialNumber: 'WB-99-XX',
    issuedDate: '05 Nov 2025',
    validUntil: '05 Nov 2026',
    status: 'VALID',
    signatureVerified: true,
    payloadIntegrityVerified: true,
    sha256Hash: '4f53cda18c2baa0c0354bb5f9a3ecbe5ed12ab4d8e11ba873c2f11161202b945',
    issuedByOfficer: 'Insp. Sharma (ID: LM-DL-019)',
    issuedAtOffice: 'Legal Metrology Central Zone, New Delhi',
    merchantName: 'Kisan Logistics Pvt Ltd',
    merchantAddress: 'Container Depot, Tughlakabad, Delhi',
    qrPayload: 'https://mapansetu.gov.in/verify/CERT-2026-X99',
  },
  'CERT-EXP-004': {
    certificateNumber: 'CERT-EXP-004',
    instrumentId: 'INS-2025-1102',
    instrumentType: 'Fuel Dispenser Pump',
    manufacturer: 'PetroEquip Global',
    serialNumber: 'FD-XZ-2021',
    issuedDate: '01 Jan 2025',
    validUntil: '01 Jan 2026',
    status: 'EXPIRED',
    signatureVerified: true,
    payloadIntegrityVerified: true,
    sha256Hash: '1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b',
    issuedByOfficer: 'Officer Patel (ID: LM-DL-088)',
    issuedAtOffice: 'Legal Metrology Division, New Delhi',
    merchantName: 'Ganga Fuel Station',
    merchantAddress: 'Ring Road, South Ext, New Delhi',
    qrPayload: 'https://mapansetu.gov.in/verify/CERT-EXP-004',
  },
};

export const initialApplications: VerificationApplication[] = [
  {
    id: 'APP-2026-041',
    businessName: 'Demo Retail Store',
    instrumentId: 'INS-2025-8839',
    instrumentType: 'Electronic Weighing Scale',
    state: 'ASSIGNED',
    officer: 'Insp. Sharma',
    officerRole: 'Senior Verification Officer',
    submittedDate: 'Oct 24, 2026',
    scheduledDate: 'Oct 28, 2026',
    feePaid: 450,
    location: 'Sector 14, New Delhi',
    remarks: 'Annual verification renewal due.',
  },
  {
    id: 'APP-2026-038',
    businessName: 'Demo Retail Store',
    instrumentId: 'INS-2025-1102',
    instrumentType: 'Fuel Dispenser Pump',
    state: 'SUBMITTED',
    officer: undefined,
    submittedDate: 'Oct 22, 2026',
    feePaid: 1200,
    location: 'Ring Road, South Ext, New Delhi',
    remarks: 'New dispenser flowmeter calibration.',
  },
  {
    id: 'APP-2026-035',
    businessName: 'Demo Retail Store',
    instrumentId: 'INS-2025-8839',
    instrumentType: 'Standard Weight Set',
    state: 'APPROVED',
    officer: 'Officer Patel',
    submittedDate: 'Oct 18, 2026',
    scheduledDate: 'Oct 18, 2026',
    feePaid: 350,
    location: 'Sector 14, New Delhi',
    remarks: 'Verification completed and passed.',
  },
  {
    id: 'APP-2026-030',
    businessName: 'Demo Retail Store',
    instrumentId: 'INST-2026-98241',
    instrumentType: 'Electronic Weighing Scale',
    state: 'APPROVED',
    officer: 'Inspector Ramesh Kumar',
    submittedDate: 'Oct 10, 2026',
    scheduledDate: 'Oct 14, 2026',
    feePaid: 450,
    location: 'G-Block Market, New Delhi',
    remarks: 'Initial calibration verification approved.',
  },
  {
    id: '#APP-8832',
    businessName: 'Metro Retail Co.',
    instrumentId: 'INS-2025-8839',
    instrumentType: 'Class III Weighing',
    state: 'ASSIGNED',
    officer: 'Insp. Sharma',
    submittedDate: 'Oct 25, 2026',
    scheduledDate: 'Oct 29, 2026',
    feePaid: 500,
    location: 'North Zone, Delhi',
    remarks: 'Assigned to North Zone inspector.',
  },
  {
    id: '#APP-8831',
    businessName: 'Kisan Logistics',
    instrumentId: 'INS-2024-7741',
    instrumentType: 'Weighbridge',
    state: 'SUBMITTED',
    officer: undefined,
    submittedDate: 'Oct 25, 2026',
    feePaid: 2500,
    location: 'Tughlakabad ICD, Delhi',
    remarks: 'Awaiting inspector assignment.',
  },
  {
    id: '#APP-8829',
    businessName: 'Ganga Fuel Station',
    instrumentId: 'INS-2025-1102',
    instrumentType: 'Flow Meter',
    state: 'IN PROGRESS',
    officer: 'Officer Patel',
    submittedDate: 'Oct 20, 2026',
    scheduledDate: 'Oct 26, 2026',
    feePaid: 1500,
    location: 'South Ext, Delhi',
    remarks: 'Field test scheduled.',
  },
  {
    id: '#APP-8825',
    businessName: 'Local Grocers',
    instrumentId: 'INS-2026-101',
    instrumentType: 'Mechanical Scale',
    state: 'DRAFT',
    submittedDate: 'Oct 15, 2026',
    feePaid: 0,
    location: 'Chandni Chowk, Delhi',
    remarks: 'Application draft in progress.',
  },
  {
    id: 'APP-2026-001',
    businessName: 'Global Tech Solutions',
    instrumentId: 'INS-GTS-01',
    instrumentType: 'Digital Weighing Scale Class II',
    state: 'ASSIGNED',
    officer: 'Insp. Sharma',
    submittedDate: 'Oct 10, 2026',
    scheduledDate: 'Oct 12, 2026',
    feePaid: 450,
    location: 'Nehru Place, New Delhi',
  },
  {
    id: 'APP-2026-002',
    businessName: 'Apex Manufacturing',
    instrumentId: 'INS-APX-88',
    instrumentType: 'Industrial Flow Meter',
    state: 'SUBMITTED',
    officer: undefined,
    submittedDate: 'Oct 12, 2026',
    feePaid: 1800,
    location: 'Mayapuri Industrial Area, New Delhi',
  },
  {
    id: 'APP-2026-003',
    businessName: 'City Supermart',
    instrumentId: 'INS-CSM-44',
    instrumentType: 'Electronic Cash Register',
    state: 'SCHEDULED',
    officer: 'Officer Patel',
    submittedDate: 'Oct 11, 2026',
    scheduledDate: 'Oct 15, 2026',
    feePaid: 600,
    location: 'Connaught Place, New Delhi',
  },
  {
    id: 'APP-2026-004',
    businessName: 'National Logistics',
    instrumentId: 'INS-NL-900',
    instrumentType: 'Weighbridge 50T',
    state: 'ASSIGNED',
    officer: 'Insp. Sharma',
    submittedDate: 'Oct 14, 2026',
    scheduledDate: 'Oct 18, 2026',
    feePaid: 2500,
    location: 'Dwarka Sector 21, New Delhi',
  },
];

export const initialOfficers: Officer[] = [
  {
    id: 'o1',
    name: 'Inspector Ramesh Kumar',
    badgeNumber: 'LM-DL-042',
    designation: 'Senior Legal Metrology Officer',
    jurisdiction: 'North & Central Delhi Zone',
    assignedCount: 6,
    status: 'Available',
    contact: '+91 98110 44201',
  },
  {
    id: 'o2',
    name: 'Insp. Sharma',
    badgeNumber: 'LM-DL-019',
    designation: 'Field Inspection Specialist',
    jurisdiction: 'South & West Delhi Zone',
    assignedCount: 8,
    status: 'On Field',
    contact: '+91 98765 19022',
  },
  {
    id: 'o3',
    name: 'Officer Patel',
    badgeNumber: 'LM-DL-088',
    designation: 'Volumetric & Flow Meter Inspector',
    jurisdiction: 'Industrial & Fuel Stations Zone',
    assignedCount: 4,
    status: 'Available',
    contact: '+91 98223 88104',
  },
  {
    id: 'o4',
    name: 'Officer Sunita Rao',
    badgeNumber: 'LM-DL-095',
    designation: 'Standards & Calibration Officer',
    jurisdiction: 'High Precision / Class I & II',
    assignedCount: 3,
    status: 'Available',
    contact: '+91 98450 95112',
  },
];

export const initialAuditLogs: AuditLog[] = [
  {
    id: 'aud-1',
    title: 'Officer Assignment',
    description: 'Officer Sharma assigned to APP-8832 in North Zone.',
    timestamp: '10 mins ago',
    actor: 'Admin (admin@mapansetu.gov.in)',
    category: 'assignment',
    severity: 'info',
  },
  {
    id: 'aud-2',
    title: 'System Settings Updated',
    description: 'Admin modified recalibration threshold for Class II devices.',
    timestamp: '1 hr ago',
    actor: 'Admin (admin@mapansetu.gov.in)',
    category: 'settings',
    severity: 'info',
  },
  {
    id: 'aud-3',
    title: 'Audit Triggered',
    description: 'Random audit initiated for 50 records in West Region.',
    timestamp: '3 hrs ago',
    actor: 'Superintendent of Legal Metrology',
    category: 'audit',
    severity: 'warning',
  },
  {
    id: 'aud-4',
    title: 'Certificate Minted & Signed',
    description: 'Digital seal generated for CERT-DEMO-001 with SHA-256 fingerprint.',
    timestamp: 'Yesterday',
    actor: 'Inspector Ramesh Kumar',
    category: 'verification',
    severity: 'success',
  },
  {
    id: 'aud-5',
    title: 'QR Code Tamper Check',
    description: 'Public query executed for INS-2025-8839. Integrity score: 100%.',
    timestamp: 'Yesterday',
    actor: 'Public Verification Node',
    category: 'system',
    severity: 'info',
  },
];

export const initialNotifications: NotificationItem[] = [
  {
    id: 'notif-1',
    title: 'Certificate expiring soon',
    message: "Certificate CERT-992 for 'Electronic Weighing Scale' expires in 7 days.",
    timeAgo: '2 hours ago',
    type: 'warning',
    read: false,
  },
  {
    id: 'notif-2',
    title: 'Application Assigned',
    message: 'Application APP-2026-041 has been assigned to an inspector.',
    timeAgo: 'Yesterday',
    type: 'info',
    read: false,
  },
  {
    id: 'notif-3',
    title: 'Verification Successful',
    message: "Your instrument 'Standard Weight Set' has passed verification.",
    timeAgo: 'Oct 18, 2026',
    type: 'success',
    read: true,
  },
];
