# Generated by Django 6.1 on 2026-09-26 11:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LicenseApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('application_number', models.CharField(max_length=30, unique=True)),
                ('category', models.CharField(choices=[('MANUFACTURER', 'Manufacturer'), ('DEALER', 'Dealer'), ('REPAIRER', 'Repairer'), ('PACKER_IMPORTER', 'Packer/Importer')], max_length=20)),
                ('license_type', models.CharField(choices=[('NEW', 'New'), ('RENEWAL', 'Renewal'), ('AMENDMENT', 'Amendment'), ('DUPLICATE', 'Duplicate')], max_length=15)),
                ('validity_years', models.PositiveSmallIntegerField(default=1)),
                ('state', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('QUERY_RAISED', 'Query Raised'), ('INSPECTION_SCHEDULED', 'Inspection Scheduled'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=25)),
                ('query_details', models.TextField(blank=True)),
                ('query_response', models.TextField(blank=True)),
                ('inspection_date', models.DateTimeField(blank=True, null=True)),
                ('inspection_report', models.TextField(blank=True)),
                ('approval_date', models.DateField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('premises_address', models.TextField()),
                ('premises_proof_type', models.CharField(max_length=30)),
                ('gst_number', models.CharField(blank=True, max_length=15)),
                ('pan_number', models.CharField(blank=True, max_length=10)),
                ('model_approval_number', models.CharField(blank=True, max_length=50)),
                ('machinery_list', models.JSONField(blank=True, default=list)),
                ('technical_staff_count', models.PositiveIntegerField(default=0)),
                ('qualification_details', models.TextField(blank=True)),
                ('equipment_list', models.JSONField(blank=True, default=list)),
                ('dealership_authorization', models.CharField(blank=True, max_length=200)),
                ('commodity_list', models.JSONField(blank=True, default=list)),
                ('iec_code', models.CharField(blank=True, max_length=15)),
                ('sample_labels', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='license_applications', to='businesses.business')),
                ('reviewing_officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='license_reviews', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submitted_license_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('license_number', models.CharField(max_length=30, unique=True)),
                ('category', models.CharField(choices=[('MANUFACTURER', 'Manufacturer'), ('DEALER', 'Dealer'), ('REPAIRER', 'Repairer'), ('PACKER_IMPORTER', 'Packer/Importer')], max_length=20)),
                ('issued_date', models.DateField()),
                ('valid_from', models.DateField()),
                ('valid_until', models.DateField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('SUSPENDED', 'Suspended'), ('CANCELLED', 'Cancelled'), ('RENEWAL_PENDING', 'Renewal Pending')], default='ACTIVE', max_length=20)),
                ('conditions', models.JSONField(blank=True, default=list)),
                ('digital_signature', models.TextField(blank=True)),
                ('payload_hash', models.CharField(blank=True, max_length=64)),
                ('qr_verification_url', models.URLField(blank=True)),
                ('pdf_object_key', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='licenses', to='businesses.business')),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='issued_license', to='licensing.licenseapplication')),
            ],
        ),
        migrations.CreateModel(
            name='LicenseDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('PREMISES_PROOF', 'Premises Proof'), ('IDENTITY_PAN', 'PAN'), ('IDENTITY_AADHAAR', 'Aadhaar'), ('GST_CERTIFICATE', 'GST Certificate'), ('INCORPORATION_CERT', 'Incorporation Certificate'), ('PARTNERSHIP_DEED', 'Partnership Deed'), ('MODEL_APPROVAL', 'Model Approval'), ('QUALIFICATION_CERT', 'Qualification Certificate'), ('EQUIPMENT_LIST', 'Equipment List'), ('FACTORY_LICENSE', 'Factory License'), ('TRADE_LICENSE', 'Trade License'), ('DEALERSHIP_AUTH', 'Dealership Authorization'), ('IEC_CERTIFICATE', 'IEC Certificate'), ('AFFIDAVIT', 'Affidavit'), ('SITE_MAP', 'Site Map'), ('SAMPLE_LABEL', 'Sample Label'), ('OTHER', 'Other')], max_length=30)),
                ('object_key', models.CharField(max_length=200, unique=True)),
                ('original_file_name', models.CharField(max_length=255)),
                ('mime_type', models.CharField(max_length=100)),
                ('size_bytes', models.PositiveIntegerField()),
                ('sha256', models.CharField(max_length=64)),
                ('verification_status', models.CharField(choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], default='PENDING', max_length=15)),
                ('verification_note', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='licensing.licenseapplication')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
