# Generated by Django 6.1 on 2026-09-26 16:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumerComplaint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('consumer_name', models.CharField(max_length=200)),
                ('consumer_phone', models.CharField(max_length=15)),
                ('consumer_email', models.EmailField(blank=True, max_length=254)),
                ('business_name', models.CharField(max_length=200)),
                ('business_address', models.TextField()),
                ('pincode', models.CharField(max_length=6)),
                ('complaint_type', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('evidence_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('INVESTIGATING', 'Investigating'), ('RESOLVED', 'Resolved'), ('DISMISSED', 'Dismissed')], default='PENDING', max_length=20)),
                ('resolution_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_complaints', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EnforcementAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('SURPRISE_INSPECTION', 'Surprise Inspection'), ('COMPLAINT_INVESTIGATION', 'Complaint Investigation'), ('RAID', 'Raid')], max_length=50)),
                ('unregistered_business_name', models.CharField(blank=True, max_length=200)),
                ('address', models.TextField()),
                ('action_date', models.DateTimeField()),
                ('findings', models.TextField()),
                ('seizure_memo_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enforcement_actions', to='businesses.business')),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enforcement_actions', to=settings.AUTH_USER_MODEL)),
                ('related_complaint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions', to='enforcement.consumercomplaint')),
            ],
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notice_number', models.CharField(max_length=100, unique=True)),
                ('violation_sections', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('ISSUED', 'Issued'), ('COMPOUNDED', 'Compounded'), ('PROSECUTED', 'Prosecuted'), ('CLOSED', 'Closed')], default='ISSUED', max_length=20)),
                ('compounding_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('due_date', models.DateField()),
                ('issue_date', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enforcement_action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notices', to='enforcement.enforcementaction')),
            ],
        ),
    ]
