# Generated by Django 6.1 on 2026-09-04 09:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_operation_id', models.UUIDField(unique=True)),
                ('entity_type', models.CharField(choices=[('INSPECTION', 'Inspection'), ('APPLICATION', 'Application')], max_length=15)),
                ('entity_id', models.CharField(max_length=100)),
                ('operation_type', models.CharField(choices=[('CREATE_INSPECTION', 'Start inspection'), ('UPSERT_CHECKLIST', 'Checklist'), ('UPSERT_READINGS', 'Readings'), ('UPLOAD_EVIDENCE', 'Evidence'), ('RECORD_DECISION', 'Decision')], max_length=20)),
                ('payload', models.JSONField(default=dict)),
                ('payload_hash', models.CharField(max_length=64)),
                ('expected_server_version', models.PositiveIntegerField(blank=True, null=True)),
                ('client_created_at', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('attempt_count', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('SYNCING', 'Syncing'), ('SYNCED', 'Synced'), ('FAILED', 'Failed'), ('CONFLICT', 'Conflict')], default='SYNCING', max_length=10)),
                ('last_error', models.TextField(blank=True, max_length=500)),
                ('server_entity_type', models.CharField(blank=True, max_length=15)),
                ('server_entity_id', models.UUIDField(blank=True, null=True)),
                ('server_version', models.PositiveIntegerField(blank=True, null=True)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sync_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-received_at'],
                'indexes': [models.Index(fields=['submitted_by', 'status', '-received_at'], name='sync_syncre_submitt_af9a67_idx')],
            },
        ),
    ]
