# Generated by Django 6.1 on 2026-09-04 08:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scheduled_at', models.DateTimeField()),
                ('schedule_note', models.TextField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('CONFIRMED', 'Confirmed'), ('RESCHEDULED', 'Rescheduled (superseded)'), ('CANCELLED', 'Cancelled')], default='CONFIRMED', max_length=15)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('end_reason', models.TextField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedules', to='applications.application')),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedules', to=settings.AUTH_USER_MODEL)),
                ('scheduled_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['scheduled_at'],
                'indexes': [models.Index(fields=['officer', 'scheduled_at'], name='scheduling__officer_6f01b9_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'CONFIRMED')), fields=('application',), name='one_confirmed_schedule_per_application')],
            },
        ),
    ]
