# Generated by Django 6.1 on 2026-09-26 16:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jurisdiction', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SealInventory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('seal_type', models.CharField(choices=[('LEAD', 'Lead Seal'), ('PAPER', 'Paper Seal'), ('HOLOGRAPHIC', 'Holographic Seal'), ('DIGITAL', 'Digital e-Seal')], max_length=20)),
                ('series_prefix', models.CharField(max_length=10)),
                ('starting_number', models.PositiveBigIntegerField()),
                ('ending_number', models.PositiveBigIntegerField()),
                ('received_date', models.DateField(auto_now_add=True)),
                ('is_fully_allocated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seal_inventories', to='jurisdiction.state')),
            ],
        ),
        migrations.CreateModel(
            name='SealAllocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('starting_number', models.PositiveBigIntegerField()),
                ('ending_number', models.PositiveBigIntegerField()),
                ('allocation_date', models.DateTimeField(auto_now_add=True)),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seal_allocations', to=settings.AUTH_USER_MODEL)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='standards.sealinventory')),
            ],
        ),
        migrations.CreateModel(
            name='VerificationStandard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('standard_type', models.CharField(choices=[('REFERENCE', 'Reference Standard'), ('SECONDARY', 'Secondary Standard'), ('WORKING', 'Working Standard')], max_length=20)),
                ('equipment_name', models.CharField(max_length=200)),
                ('identification_number', models.CharField(max_length=100, unique=True)),
                ('calibration_date', models.DateField()),
                ('next_calibration_due', models.DateField()),
                ('calibrated_by', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_standards', to='jurisdiction.state')),
            ],
        ),
    ]
