# Generated by Django 6.1 on 2026-08-30 09:12

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('instrument_number', models.CharField(max_length=50)),
                ('serial_number', models.CharField(max_length=50)),
                ('instrument_type', models.CharField(choices=[('ELECTRONIC_SCALE', 'Electronic scale'), ('WEIGHBRIDGE', 'Weighbridge'), ('FUEL_DISPENSER', 'Fuel dispenser'), ('BEAM_SCALE', 'Beam scale'), ('WEIGHT_SET', 'Weight set'), ('MEASURING_TAPE', 'Measuring tape'), ('OTHER', 'Other')], max_length=20)),
                ('manufacturer', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('capacity', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(0.001)])),
                ('capacity_unit', models.CharField(max_length=10)),
                ('location', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('REGISTERED', 'Registered'), ('PENDING_VERIFICATION', 'Pending verification'), ('VERIFIED', 'Verified'), ('INACTIVE', 'Inactive')], default='REGISTERED', max_length=20)),
                ('next_due_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instruments', to='businesses.business')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('business', 'instrument_number'), name='unique_instrument_number_per_business'), models.UniqueConstraint(fields=('business', 'serial_number'), name='unique_serial_number_per_business')],
            },
        ),
    ]
