# Generated by Django 6.1 on 2026-08-31 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='instrument_type',
            field=models.CharField(choices=[('ELECTRONIC_SCALE', 'Electronic scale'), ('PLATFORM_SCALE', 'Platform scale (industrial)'), ('COUNTER_SCALE', 'Counter scale (retail)'), ('WEIGHBRIDGE', 'Weighbridge'), ('SPRING_BALANCE', 'Spring balance (mechanical)'), ('FUEL_DISPENSER', 'Fuel dispenser'), ('BEAM_SCALE', 'Beam scale'), ('WEIGHT_SET', 'Weight set'), ('MEASURING_TAPE', 'Measuring tape'), ('OTHER', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('PENDING_VERIFICATION', 'Pending verification'), ('EXPIRED', 'Expired'), ('REJECTED', 'Rejected'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=20),
        ),
    ]
