# Generated by Django 6.1 on 2026-08-31 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0002_alter_instrument_instrument_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='status',
            field=models.CharField(choices=[('REGISTERED', 'Registered — not yet verified'), ('ACTIVE', 'Active — verification current'), ('PENDING_VERIFICATION', 'Pending verification'), ('EXPIRED', 'Expired'), ('REJECTED', 'Rejected'), ('INACTIVE', 'Inactive')], default='REGISTERED', max_length=20),
        ),
    ]
