# Generated by Django 6.1 on 2026-09-26 16:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('state_code', models.CharField(default='NAT', max_length=5)),
                ('service_type', models.CharField(choices=[('MANUFACTURER_LICENSE_NEW', 'New Manufacturer License'), ('MANUFACTURER_LICENSE_RENEWAL', 'Manufacturer License Renewal'), ('DEALER_LICENSE_NEW', 'New Dealer License'), ('DEALER_LICENSE_RENEWAL', 'Dealer License Renewal'), ('REPAIRER_LICENSE_NEW', 'New Repairer License'), ('REPAIRER_LICENSE_RENEWAL', 'Repairer License Renewal'), ('PACKER_REGISTRATION', 'Packer Registration'), ('VERIFICATION_FEE', 'Verification Fee'), ('DUPLICATE_LICENSE', 'Duplicate License'), ('AMENDMENT_FEE', 'Amendment Fee'), ('COMPOUNDING_FEE', 'Compounding Fee')], max_length=40)),
                ('instrument_category', models.CharField(blank=True, max_length=50)),
                ('base_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('per_year_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('late_surcharge_percent', models.DecimalField(decimal_places=2, default=100, max_digits=5)),
                ('gst_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('effective_from', models.DateField()),
                ('effective_until', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_fee_schedules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-effective_from'],
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_reference', models.CharField(max_length=50, unique=True)),
                ('service_type', models.CharField(choices=[('MANUFACTURER_LICENSE_NEW', 'New Manufacturer License'), ('MANUFACTURER_LICENSE_RENEWAL', 'Manufacturer License Renewal'), ('DEALER_LICENSE_NEW', 'New Dealer License'), ('DEALER_LICENSE_RENEWAL', 'Dealer License Renewal'), ('REPAIRER_LICENSE_NEW', 'New Repairer License'), ('REPAIRER_LICENSE_RENEWAL', 'Repairer License Renewal'), ('PACKER_REGISTRATION', 'Packer Registration'), ('VERIFICATION_FEE', 'Verification Fee'), ('DUPLICATE_LICENSE', 'Duplicate License'), ('AMENDMENT_FEE', 'Amendment Fee'), ('COMPOUNDING_FEE', 'Compounding Fee')], max_length=40)),
                ('related_entity_type', models.CharField(max_length=30)),
                ('related_entity_id', models.UUIDField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fee_breakdown', models.JSONField(blank=True, default=dict)),
                ('gateway', models.CharField(default='DEMO', max_length=20)),
                ('gateway_order_id', models.CharField(blank=True, max_length=100)),
                ('gateway_payment_id', models.CharField(blank=True, max_length=100)),
                ('gateway_signature', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('INITIATED', 'Initiated'), ('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], default='INITIATED', max_length=15)),
                ('receipt_url', models.URLField(blank=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payer_business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='businesses.business')),
                ('payer_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='initiated_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
