# Generated by Django 6.1 on 2026-09-26 16:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('name_local', models.CharField(blank=True, max_length=200)),
                ('headquarters_city', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=5, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('name_local', models.CharField(blank=True, max_length=200)),
                ('official_language', models.CharField(default='hi', max_length=20)),
                ('controller_email', models.EmailField(blank=True, max_length=254)),
                ('controller_phone', models.CharField(blank=True, max_length=15)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('name_local', models.CharField(blank=True, max_length=200)),
                ('pin_codes', models.JSONField(blank=True, default=list)),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='districts', to='jurisdiction.division')),
            ],
        ),
        migrations.CreateModel(
            name='JurisdictionAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('designation', models.CharField(choices=[('CONTROLLER', 'Controller'), ('ADDITIONAL_CONTROLLER', 'Additional Controller'), ('JOINT_CONTROLLER', 'Joint Controller'), ('DEPUTY_CONTROLLER', 'Deputy Controller'), ('ACLM', 'Assistant Controller'), ('SLMO', 'Senior LMO'), ('LMO', 'LMO')], max_length=30)),
                ('is_primary', models.BooleanField(default=True)),
                ('active_from', models.DateField()),
                ('active_until', models.DateField(blank=True, null=True)),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='jurisdiction.district')),
                ('division', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='jurisdiction.division')),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jurisdiction_assignments', to=settings.AUTH_USER_MODEL)),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='jurisdiction.state')),
            ],
            options={
                'ordering': ['-active_from'],
            },
        ),
        migrations.AddField(
            model_name='division',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='divisions', to='jurisdiction.state'),
        ),
    ]
