# Generated by Django 6.1 on 2026-09-04 09:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inspections', '0001_initial'),
        ('instruments', '0003_alter_instrument_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('evidence_type', models.CharField(choices=[('MACHINE_PHOTO', 'Instrument photo'), ('NAMEPLATE_PHOTO', 'Nameplate / serial plate'), ('SEAL_PHOTO', 'Verification seal'), ('SITE_PHOTO', 'Site / premises'), ('DOCUMENT', 'Supporting document')], max_length=20)),
                ('object_key', models.CharField(max_length=255, unique=True)),
                ('original_file_name', models.CharField(max_length=255)),
                ('mime_type', models.CharField(max_length=50)),
                ('size_bytes', models.PositiveIntegerField()),
                ('sha256', models.CharField(max_length=64)),
                ('captured_at', models.DateTimeField(blank=True, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('gps_accuracy_meters', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=500)),
                ('client_operation_id', models.UUIDField(blank=True, null=True, unique=True)),
                ('status', models.CharField(choices=[('UPLOADED', 'Uploaded')], default='UPLOADED', max_length=10)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evidence', to='inspections.inspection')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evidence', to='instruments.instrument')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evidence_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'evidence',
                'ordering': ['uploaded_at'],
            },
        ),
    ]
