import uuid

from django.conf import settings
from django.db import models


class Evidence(models.Model):
    """A photo or document captured during an Inspection (DATA_MODEL.md — Evidence).

    The binary lives in object storage (MinIO via the S3 API, or the local
    filesystem until MINIO_ENDPOINT is set — ADR-007). This row is the metadata
    and the integrity record: `sha256` is computed by the server over the bytes
    it actually stored, so a later reader can prove the file is the one the
    officer uploaded.

    `object_key` is generated by the server. A client never chooses where a
    file lands.
    """

    class Type(models.TextChoices):
        MACHINE_PHOTO = "MACHINE_PHOTO", "Instrument photo"
        NAMEPLATE_PHOTO = "NAMEPLATE_PHOTO", "Nameplate / serial plate"
        SEAL_PHOTO = "SEAL_PHOTO", "Verification seal"
        SITE_PHOTO = "SITE_PHOTO", "Site / premises"
        DOCUMENT = "DOCUMENT", "Supporting document"

    class Status(models.TextChoices):
        UPLOADED = "UPLOADED", "Uploaded"

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)

    inspection = models.ForeignKey(
        "inspections.Inspection", on_delete=models.PROTECT, related_name="evidence"
    )
    # Denormalised from the inspection's application so an instrument's
    # history can list its evidence without walking three joins.
    instrument = models.ForeignKey(
        "instruments.Instrument", on_delete=models.PROTECT, related_name="evidence"
    )
    uploaded_by = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.PROTECT, related_name="evidence_uploaded"
    )

    evidence_type = models.CharField(max_length=20, choices=Type.choices)

    object_key = models.CharField(max_length=255, unique=True)
    original_file_name = models.CharField(max_length=255)
    mime_type = models.CharField(max_length=50)
    size_bytes = models.PositiveIntegerField()
    sha256 = models.CharField(max_length=64)

    # Device-side facts. Null means "not captured", never 0,0 or "now".
    captured_at = models.DateTimeField(null=True, blank=True)
    latitude = models.DecimalField(max_digits=9, decimal_places=6, null=True, blank=True)
    longitude = models.DecimalField(max_digits=9, decimal_places=6, null=True, blank=True)
    gps_accuracy_meters = models.PositiveIntegerField(null=True, blank=True)

    notes = models.CharField(max_length=500, blank=True)

    # Offline replay key: the same operation submitted twice returns the
    # original row instead of storing the file again.
    client_operation_id = models.UUIDField(null=True, blank=True, unique=True)

    status = models.CharField(max_length=10, choices=Status.choices, default=Status.UPLOADED)

    uploaded_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["uploaded_at"]
        verbose_name_plural = "evidence"

    def __str__(self):
        return f"{self.evidence_type} {self.original_file_name} ({self.inspection_id})"
