# Generated by Django 6.1 on 2026-08-30 15:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('sequence', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('event_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('actor_role', models.CharField(blank=True, max_length=10)),
                ('action', models.CharField(max_length=80)),
                ('entity_type', models.CharField(max_length=50)),
                ('entity_id', models.CharField(max_length=64)),
                ('timestamp', models.DateTimeField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('previous_hash', models.CharField(blank=True, max_length=64)),
                ('current_hash', models.CharField(max_length=64)),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-sequence'],
            },
        ),
    ]
