# Generated by Django 6.1 on 2026-08-31 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditlog',
            name='actor_user',
        ),
        migrations.AddField(
            model_name='auditlog',
            name='actor_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='actor_user_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
