# Generated by Django 6.1 on 2026-08-31 06:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
        ('businesses', '0001_initial'),
        ('inspections', '0001_initial'),
        ('instruments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('certificate_number', models.CharField(max_length=40, unique=True)),
                ('issued_at', models.DateTimeField()),
                ('valid_until', models.DateTimeField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('REVOKED', 'Revoked')], default='ACTIVE', max_length=10)),
                ('payload_version', models.CharField(default='1', max_length=10)),
                ('canonical_payload', models.TextField()),
                ('payload_hash', models.CharField(max_length=64)),
                ('digital_signature', models.TextField()),
                ('signature_algorithm', models.CharField(default='RSASSA-PSS-SHA256', max_length=50)),
                ('public_key_reference', models.CharField(default='prototype-key-1', max_length=100)),
                ('pdf_object_key', models.CharField(blank=True, max_length=255)),
                ('qr_verification_url', models.URLField(blank=True, max_length=500)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revocation_reason', models.TextField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='certificate', to='applications.application')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='certificates', to='businesses.business')),
                ('inspection', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='certificate', to='inspections.inspection')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='certificates', to='instruments.instrument')),
            ],
            options={
                'ordering': ['-issued_at'],
            },
        ),
    ]
